Modificado agenetes para que lea el path correctamente

diff --git a/Jenkinsfile_agentes b/Jenkinsfile_agentes
--- a/Jenkinsfile_agentes
+++ b/Jenkinsfile_agentes
@@ -1,53 +1,52 @@
 pipeline {
     agent none
-    
-    environment {
-    PATH = "/home/agente1/.local/bin:$PATH"
-    }
+
     stages {
         stage('Get Code') {
             agent { label 'agente1' }
             steps {
-                sh 'whoami'
-                sh 'hostname'
-                git branch: 'develop', url: 'https://github.com/socche/todo-list-aws.git'
-                sh 'git clone --single-branch --branch staging https://github.com/socche/todo-list-aws-config.git config'
-                sh 'cp config/samconfig.toml .'
-
+                withEnv(["PATH=/home/agente1/.local/bin:$PATH"]) {
+                    sh 'whoami'
+                    sh 'hostname'
+                    git branch: 'develop', url: 'https://github.com/socche/todo-list-aws.git'
+                    sh 'git clone --single-branch --branch staging https://github.com/socche/todo-list-aws-config.git config'
+                    sh 'cp config/samconfig.toml .'
+                }
             }
         }
 
         stage('Static Test') {
             agent { label 'agente1' }
             steps {
-                sh 'whoami'
-                sh 'hostname'
-                echo 'Running flake8...'
-                sh 'flake8 src/ || true'
-                
-                echo 'Running bandit...'
-                sh 'bandit -r src/ || true'
+                withEnv(["PATH=/home/agente1/.local/bin:$PATH"]) {
+                    sh 'whoami'
+                    sh 'hostname'
+                    echo 'Running flake8...'
+                    sh 'flake8 src/ || true'
+
+                    echo 'Running bandit...'
+                    sh 'bandit -r src/ || true'
+                }
             }
         }
 
         stage('Deploy (Staging)') {
             agent { label 'agente1' }
-            environment {
-                PATH = "/home/agente1/.local/bin:$PATH"
-            }
             steps {
-                sh 'whoami'
-                sh 'hostname'
-                echo 'Building project with SAM...'
-                sh 'sam build'
+                withEnv(["PATH=/home/agente1/.local/bin:$PATH"]) {
+                    sh 'whoami'
+                    sh 'hostname'
+                    echo 'Building project with SAM...'
+                    sh 'sam build'
 
-                echo 'Validating template...'
-                sh 'sam validate --region us-east-1'
+                    echo 'Validating template...'
+                    sh 'sam validate --region us-east-1'
 
-                echo 'Deploying to Staging environment (expecting failure)...'
-                sh 'sam deploy --config-env staging --no-confirm-changeset || true'
+                    echo 'Deploying to Staging environment (expecting failure)...'
+                    sh 'sam deploy --config-env staging --no-confirm-changeset || true'
 
-                stash name: 'workspace-ci', includes: '**/*'
+                    stash name: 'workspace-ci', includes: '**/*'
+                }
             }
         }
 
@@ -55,18 +54,19 @@ pipeline {
             agent { label 'agente2' }
             environment {
                 BASE_URL = 'https://iw3lwsx0mj.execute-api.us-east-1.amazonaws.com/Prod'
-                PATH = "/home/agente2/.local/bin:$PATH"
             }
             steps {
-                unstash 'workspace-ci'
-                sh 'whoami'
-                sh 'hostname'
+                withEnv(["PATH=/home/agente2/.local/bin:$PATH"]) {
+                    unstash 'workspace-ci'
+                    sh 'whoami'
+                    sh 'hostname'
 
-                echo 'Running REST integration tests...'
-                sh 'pytest --junitxml=report.xml test/integration/todoApiTest.py'
+                    echo 'Running REST integration tests...'
+                    sh 'pytest --junitxml=report.xml test/integration/todoApiTest.py'
 
-                echo 'Publicando resultados...'
-                junit 'report.xml'
+                    echo 'Publicando resultados...'
+                    junit 'report.xml'
+                }
             }
         }
     }
